[default]
IS_DEVE = true
BASE_URL = "https://www.google.com/"
HOME_DIR = "C:\\Users\\haiju\\Dropbox\\kfbuy\\web_project\\search_by_image"
PUSH_URL_WITH_SBI_REDIS_KEY = "PUSH_URL_WITH_SBI_REDIS_KEY"
USER_AGENT = [ "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36",]

[default.REDIS]
HOST = "localhost"
PORT = 6379
DB = 4
PASSWD = ""

[default.MYSQL]
HOST = ""
USER = ""
PASSWD = ""
DATABASE = ""
PORT = 3306
